version: '3'

tasks:
  test:
    cmds:
      - go test -v ./...

  fmt:
    cmds:
      - go fmt ./...

  install:
    vars:
      DEST: '{{.DEST | default "~/bin/"}}'
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0-devel"
    cmds:
      - go build -ldflags "-X main.version={{.VERSION}}" -o jira-newbranch main.go
      - mkdir -p {{.DEST}}
      - mv jira-newbranch {{.DEST}}

  go-install:
    desc: "Installs the binary using standard go install"
    cmds:
      - go install .
